# Generated by Django 3.0.4 on 2020-04-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_memberrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(default='green', max_length=20),
        ),
    ]
