# Generated by Django 3.0.4 on 2020-04-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_membership_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='memberrequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='accounts.Profile'),
        ),
    ]
