# Generated by Django 3.0.4 on 2020-04-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20200324_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='categor',
            new_name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='red', max_length=20),
        ),
    ]
