# Generated by Django 3.0.4 on 2020-04-07 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0006_auto_20200407_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='users',
        ),
    ]
